apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the University Application
name: university
version: 0.1.0
maintainers:
  - name: Jee Vang, Ph.D.
    email: vangjee@gmail.com
    url: https://github.com/vangj